// Placeholder type declarations for the wasm-bindgen module. The
// real `.d.ts` is generated by `build-wasm.sh` and overwrites this
// file on each run. Checked in so `tsc -b` passes against a fresh
// checkout without requiring the WASM build to have run yet.
//
// If you edit this file, your changes will be lost the next time
// `build-wasm.sh` runs — sync into idml-introspect-wasm's exported
// surface instead.

export class Inspector {
  constructor(idml: Uint8Array);
  tree(): string;
  properties(node_json: string): string;
  apply(mutation_json: string): string;
  renderPage(page_index: number, dpi: number): Uint8Array;
  free(): void;
}

export default function init(url?: string | URL): Promise<unknown>;
