/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_inspector_free: (a: number, b: number) => void;
export const inspector_apply: (a: number, b: number, c: number) => [number, number, number, number];
export const inspector_new: (a: number, b: number) => [number, number, number];
export const inspector_properties: (a: number, b: number, c: number) => [number, number, number, number];
export const inspector_redo: (a: number) => [number, number, number, number];
export const inspector_renderPage: (a: number, b: number, c: number) => [number, number, number, number];
export const inspector_tree: (a: number) => [number, number, number, number];
export const inspector_undo: (a: number) => [number, number, number, number];
export const on_start: () => void;
export const qcms_enable_iccv4: () => void;
export const qcms_profile_precache_output_transform: (a: number) => void;
export const qcms_transform_data_bgra_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_bgra_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgb_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgb_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgba_out_lut: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_data_rgba_out_lut_precache: (a: number, b: number, c: number, d: number) => void;
export const qcms_transform_release: (a: number) => void;
export const qcms_profile_is_bogus: (a: number) => number;
export const qcms_white_point_sRGB: (a: number) => void;
export const lut_inverse_interp16: (a: number, b: number, c: number) => number;
export const lut_interp_linear16: (a: number, b: number, c: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
