// Wire-format types for the main↔worker message channel.
//
// Every type in this file is a re-export of a tsify-generated type
// from Rust, surfaced through the published `@paged-media/canvas-wasm`
// package (Decision-B package boundary). To add a new type, derive
// `Tsify` in `crates/paged-canvas/src/channel.rs` (or the appropriate
// crate) in `paged-media/core`, cut a new `@paged-media/canvas-wasm`
// release, bump the dependency pin in `packages/client/package.json`,
// then re-export the new symbol here. Do not hand-write types in this
// file — the package's `paged_canvas_wasm.d.ts` is the source of truth;
// this barrel exists so consumers don't have to learn the wasm import
// path.
//
// CI enforces the version contract: `scripts/check-protocol-version.sh`
// compares `PROTOCOL_VERSION` below against the `ProtocolVersion` tuple
// baked into the installed package's `.d.ts` and fails on drift (see
// `.github/workflows/protocol-version.yml`).
//
// `PROTOCOL_VERSION` stays a TS constant because the canvas
// outgoing messages need a value (not a type) at runtime; the
// matching Rust constant is in `paged-canvas/src/channel.rs` and
// the published package must update in lockstep.

export const PROTOCOL_VERSION = 42 as const;

export type {
  AnchorId,
  AnchorPosition,
  AppliedOperation,
  ByteBuf,
  CameraSabLayout,
  CaretDirection,
  CaretGeometry,
  CharacterStyleSummary,
  CollectionName,
  ContentSelection,
  DocumentHandle,
  DocumentMeta,
  ExportPdfWireOptions,
  DocumentStats,
  ElementGeometryItem,
  ElementId,
  FieldChange,
  FieldKind,
  FrameBounds,
  GuideOrientationSpec,
  GestureAnchor,
  GestureFailure,
  GestureHandle,
  GestureModifiers,
  GestureSabLayout,
  GestureType,
  GradientSummary,
  HitFilter,
  HitResult,
  InvalidationHint,
  ElementProperties,
  LayerSummary,
  LayoutCacheStats,
  ArticleSummary,
  BookmarkSummary,
  CellStyleSummary,
  ColorGroupSummary,
  ColorPreview,
  ConditionSetSummary,
  ConditionSummary,
  CrossReferenceSummary,
  FontSummary,
  HyperlinkSummary,
  IndexTopicSummary,
  GuideSummary,
  LineBounds,
  LinkSummary,
  MasterPageSummary,
  PageSummary,
  ParagraphBounds,
  PathfinderKind,
  PreflightFinding,
  SectionSummary,
  SpreadSummary,
  TableHitContext,
  TableStyleSummary,
  TextCellAddr,
  ParagraphStyleSummary,
  PropertyEntry,
  SceneTreeNode,
  SceneLayer,
  SceneItem,
  ScenePathSeg,
  ScenePaint,
  StorySummary,
  SwatchSummary,
  LoadError,
  LodTier,
  MainToWorker,
  MainToWorkerKind,
  Mutation,
  NodeId,
  NodeSpec,
  NumberingListSpec,
  NumberingListSummary,
  NumberingMap,
  Operation,
  GradientDetail,
  GradientFeatherSpec,
  ParagraphRuleSpec,
  TabStopSpec,
  StyleScope,
  GradientFeatherStopSpec,
  GradientStopWire,
  InkSummary,
  PageId,
  PathAnchorSpec,
  PathAnchorsResult,
  NearestPathPointResult,
  PathAnchorTriple,
  PathPointAddress,
  PathPointRole,
  ProtocolVersion,
  PropertyPath,
  ResizeHandle,
  ResolutionResult,
  RunningHeader,
  SelectionMode,
  SelectionRect,
  SnapAxis,
  SnapLine,
  SnapshotError,
  SnapshotPng,
  SwatchSpec,
  GradientSpec,
  GradientStopSpec,
  ColorGroupSpec,
  TocEntry,
  Value,
  WordBounds,
  WorkerError,
  WorkerToMain,
  WorkerToMainKind,
} from "@paged-media/canvas-wasm";
